//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAutomationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public Nullable<System.DateTime> DrugExpiry { get; set; }
        public string Description { get; set; }
        public string Dosage { get; set; }
        public Nullable<int> DrugPrice { get; set; }
    }
}
