//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAutomationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugRequest
    {
        public int DrugRequestId { get; set; }
        public Nullable<int> DrugId { get; set; }
        public string DrugComposition { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string DrugStatus { get; set; }
    }
}
